
CREATE   PROCEDURE dbo.usp_Load_SchwabQuotes_Stage_to_SchwabQuotes
AS
/*
EXEC dbo.usp_Load_SchwabQuotes_Stage_to_SchwabQuotes;
*/
BEGIN
    SET NOCOUNT ON;

    INSERT INTO dbo.SchwabQuotes
    (
        RawId,
        AssetMainType,
        AssetSubType,
        QuoteType,
        Realtime,
        Ssid,
        Symbol,
        FundamentalAvg10DaysVolume,
        FundamentalAvg1YearVolume,
        FundamentalDivAmount,
        FundamentalDivFreq,
        FundamentalDivPayAmount,
        FundamentalDivYield,
        FundamentalEps,
        FundamentalFundLeverageFactor,
        FundamentalLastEarningsDate,
        FundamentalPeRatio,
        Quote52WeekHigh,
        Quote52WeekLow,
        QuoteAskMICId,
        QuoteAskPrice,
        QuoteAskSize,
        QuoteAskTime,
        QuoteBidMICId,
        QuoteBidPrice,
        QuoteBidSize,
        QuoteBidTime,
        QuoteClosePrice,
        QuoteHighPrice,
        QuoteLastMICId,
        QuoteLastPrice,
        QuoteLastSize,
        QuoteLowPrice,
        QuoteMark,
        QuoteMarkChange,
        QuoteMarkPercentChange,
        QuoteNetChange,
        QuoteNetPercentChange,
        QuoteOpenPrice,
        QuotePostMarketChange,
        QuotePostMarketPercentChange,
        QuoteQuoteTime,
        QuoteSecurityStatus,
        QuoteTotalVolume,
        QuoteTradeTime,
        InsertedAt,
        OperationType,
        Comments,
        BatchId,
        LoadDate,
        CreatedBy,
        CreatedOn,
        LastEditBy,
        LastEditOn
    )
    SELECT
        s.RawId,
        s.AssetMainType,
        s.AssetSubType,
        s.QuoteType,
        s.Realtime,
        s.Ssid,
        s.Symbol,
        s.FundamentalAvg10DaysVolume,
        s.FundamentalAvg1YearVolume,
        s.FundamentalDivAmount,
        s.FundamentalDivFreq,
        s.FundamentalDivPayAmount,
        s.FundamentalDivYield,
        s.FundamentalEps,
        s.FundamentalFundLeverageFactor,
        s.FundamentalLastEarningsDate,
        s.FundamentalPeRatio,
        s.Quote52WeekHigh,
        s.Quote52WeekLow,
        s.QuoteAskMICId,
        s.QuoteAskPrice,
        s.QuoteAskSize,
        s.QuoteAskTime,
        s.QuoteBidMICId,
        s.QuoteBidPrice,
        s.QuoteBidSize,
        s.QuoteBidTime,
        s.QuoteClosePrice,
        s.QuoteHighPrice,
        s.QuoteLastMICId,
        s.QuoteLastPrice,
        s.QuoteLastSize,
        s.QuoteLowPrice,
        s.QuoteMark,
        s.QuoteMarkChange,
        s.QuoteMarkPercentChange,
        s.QuoteNetChange,
        s.QuoteNetPercentChange,
        s.QuoteOpenPrice,
        s.QuotePostMarketChange,
        s.QuotePostMarketPercentChange,
        s.QuoteQuoteTime,
        s.QuoteSecurityStatus,
        s.QuoteTotalVolume,
        s.QuoteTradeTime,
        s.InsertedAt,
        'API ETL'     AS OperationType,
        NULL          AS Comments,
        NULL          AS BatchId,
        GETDATE()     AS LoadDate,
        SUSER_SNAME() AS CreatedBy,
        GETDATE()     AS CreatedOn,
        NULL          AS LastEditBy,
        NULL          AS LastEditOn
    FROM dbo.SchwabQuotes_Stage s
    WHERE NOT EXISTS
    (
        SELECT 1
        FROM dbo.SchwabQuotes q
        WHERE q.RawId = s.RawId
    );
END;

