[schwab]
app_key = YaFWAGkzRwjfhV8vPoGG0MZLvVQ5atSa52Hpzq7cl5R97Gg5
app_secret = QYYggd4ov5NRMWtosRboGA9VrKeYiCPzlGNhOpNoSADOtyGArvbkMyV4ACjWgg5s
redirect_uri = https://carfourless.com/schwab/callback
token_file = schwab_tokens.json


auth_url = https://api.schwabapi.com/v1/oauth/authorize
token_url = https://api.schwabapi.com/v1/oauth/token
quotes_url = https://api.schwabapi.com/marketdata/v1/quotes
price_history_url = https://api.schwabapi.com/marketdata/v1/pricehistory

[sqlserver]
driver = ODBC Driver 17 for SQL Server
;localhost
server = localhost
database = PBI_Projects
username = Alexb
password = Alex08540$$
trust_cert = yes

[DefaultPortfolio]
DefaultPortfolio = 1

